[project]
name = "hse-agents"
version = "0.1.0"
description = "Homework for HSE agents course"
readme = "README.md"
authors = [
    { name = "sblenlkj", email = "sblenlkj@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "nbformat",
    "pyyaml",
    "jupyter",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["fixtures*", "submission*"]